{% set name = "ipdb" %}
{% set version = "0.13.7" %}
{% set sha256 = "037a2ad43b887d340a3207452a1a2a47621d50dac67dd045fb8ca5d3e909bc6a" %}

{% set gh_org = "gotcha" %}
{% set gh_repo = name %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ gh_org }}/{{ gh_repo }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
    - ipdb = ipdb.__main__:main
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
    - call %RECIPE_DIR%/install-scripts.bat  # [win]
    - . ${RECIPE_DIR}/install-scripts.sh  # [not win]

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools

  run:
    - python >=2.7
    - ipython

test:
  imports:
    - ipdb
  commands:
    - python -c 'import os; assert(os.environ["PYTHONBREAKPOINT"] == "ipdb.set_trace")'

about:
  home: https://github.com/{{ gh_org }}/{{ gh_repo }}
  license: BSD-3-Clause
  license_file: COPYING.txt
  summary: Integration of IPython pdb

  description: |
    ipdb exports functions to access the IPython debugger,
    which features tab completion, syntax highlighting, better
    tracebacks, better introspection with the same interface
    as the pdb module.
  dev_url: https://github.com/{{ gh_org }}/{{ gh_repo }}

extra:
  recipe-maintainers:
    - vamega
