{% set name = "ipdb" %}
{% set version = "0.12.2" %}
{% set sha256 = "a15a06d32cbba2bebd4b67b3b3cf0605fb6a05e7f85c0f09de708f6fbf77d020" %}

{% set gh_org = "gotcha" %}
{% set gh_repo = name %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ gh_org }}/{{ gh_repo }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
    - ipdb = ipdb.__main__:main
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
    - call %RECIPE_DIR%/install-scripts.bat  # [win]
    - . ${RECIPE_DIR}/install-scripts.sh  # [not win]

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - ipython

test:
  imports:
    - ipdb
  commands:
    - python -c 'import os; assert(os.environ["PYTHONBREAKPOINT"] == "ipdb.set_trace")'

about:
  home: https://github.com/{{ gh_org }}/{{ gh_repo }}
  license: BSD-3
  license_file: COPYING.txt
  summary: "Integration of IPython pdb"

  description: |
    ipdb exports functions to access the IPython debugger,
    which features tab completion, syntax highlighting, better
    tracebacks, better introspection with the same interface
    as the pdb module.
  dev_url: https://github.com/{{ gh_org }}/{{ gh_repo }}

extra:
  recipe-maintainers:
    - vamega
